### ISSUE TITLE
Help!!!

### ISSUE THREAD

**Issue by tuyuritio** [nextgensparx/huawei-router-api#19]
Hey guy, I don't know whether you can see this issue...  
  
Now I have some problems with my server in my home which is connected to the **Honor Router 3**.  
I turned off the option about dmz so I can't connect to the server just now... (I am staying at school)  
The only thing I know is that the request-url is `<host>/api/ntwk/dmz` and I can't guess the parameters of it.  
With any luck, maybe you're still using this router.  
I wish I could get a little help about the parameter form...  
  
### I do appreciate your help!!!

**Comment by siphomateke** [comment]
Hello. Sorry, I haven't used a Huawei router in quite some time and can't really help you with this. But I hope you managed to fix it and wish you all the best!
