### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hzswdef** [nextgensparx/huawei-router-api#20]
# Documentation
Coming soon...

<hr />

We are waiting!

**Comment by siphomateke** [comment]
Apologies, I haven't worked on this project for about 5 years 😅. I'd recommend just exploring the code ([start here](https://github.com/siphomateke/huawei-router-api/blob/master/src/index.js)) and using your IDEs autocomplete features to see what's possible. Most methods do have JSDoc comments so should be relatively easy to use.

Hopefully that helps!
